version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.node
    container_name: nodeapp
    hostname: nodeapp
    # volumes:
      # - .:/home/nodeapp
      # - ./server:/home/nodeapp/app
    ports:
      - "3000:3000"
    tty: true

  nginx:
    restart: always
    image: nginx:alpine
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.nginx
    container_name: nginxapp
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    tty: true
    links:
      - web