FROM nginx:alpine

# Replace default config 
COPY ./.docker/nginx.template.conf /etc/nginx/conf.d/nginx.template

EXPOSE 80
CMD envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx-debug -g 'daemon off;'
